spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.vvsogddfgkzdzgxyylcg&password=wooDe.73study-buddy-api
    username: postgres.vvsogddfgkzdzgxyylcg
    password: wooDe.73study-buddy-api

---
spring:
  config:
    activate:
      on-profile: development
  devtools:
    add-properties: true
  mvc:
    log-request-details: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    debug: true
logging:
  level:
    web: DEBUG
mapping: "/**"
---
spring:
  config:
    activate:
      on-profile: production
  devtools:
    add-properties: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
mapping: "/api/v1/auth"
